version: '3'
services:
  redis:
    image: redis-example-masonic
    container_name: masonic-redis-db
    hostname: my-redis
    networks:
      - my_network


  web:
    image: k8-masonic-db
    container_name: k8-masonic-webapp
    networks:
      - my_network
    depends_on:
      - redis
    ports:
    - "8000:5001"

networks:
  my_network:
    driver: bridge