apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: masonic-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      hostname: my-redis
      containers:
      - name: redis
        image: k8-masonic-db
        imagePullPolicy: Never # Required for local deployment (not in Docker Hub)
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-storage
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: masonic-app
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  clusterIP: None  # Headless service to enable direct communication within the network