apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: masonic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      hostname: my-redis
      containers:
      - name: redis
        image: redis-example-masonic
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: masonic-app
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  clusterIP: None  # Headless service to enable direct communication within the network